### ISSUE TITLE
Unkillable enemy when enabling Unlimited Stacking of Modifiers (Stat/AC/Hit/Damage/Etc)

### ISSUE THREAD

**Issue by FajriFadli** [xADDBx/ToyBox-RogueTrader#11]
### Description of the bug

Some plot specific enemy (Warden in Rykadi Philia, Cultist Leader in Footfall. Not sure if there's more) can't be killed when Unlimited Stacking of Modifiers (Stat/AC/Hit/Damage/Etc) is enabled. I find reloading before the battle and disabling Unlimited Stacking resolve this issue.

My guess is it might mess with how events might be started after the death of these specific enemy (Chaos lenses will be activated and resurrect Warden, Argenta start dialogue with Cultist Leader) as one workaround I use before finding its related to Unlimited Stacking, is by destroying the lenses when fighting the Warden, which finally make the Warden able to be killed. No such workaround I can find when fighting the Cultist Leader until I resolve the issue by disabling Unlimited Stacking.

### Steps To Reproduce

1. Enable Unlimited Stacking
2. Fight Warden or Cultist Leader
3. Warden and Cultist Leader health won't go down beyond ~10%, they can't be killed and the fight will never end

### Toybox Version

1.5.8n

### What game are you using Toybox on?

Rogue Trader

### Game Version

1.0.62

**Comment by xADDBx** [comment]
https://github.com/xADDBx/ToyBox-RogueTrader/commit/cc518e6172ecfb50f713b697368f315935b7fd97
