### ISSUE TITLE
Spitter mutants in the Pulvis Platinum system are affected by infinite action points cheat.

### ISSUE THREAD

**Issue by Aranwen** [xADDBx/ToyBox-RogueTrader#15]
### Description of the bug

I had infinite action points on, when a spitter mutant got their turn they ran up to me and started spamming spit. because I had faster combat on and was looking away I lost 2 party members before I paused it to disable the cheat.

### Steps To Reproduce

turn on infinite actions, goto Pulvis Platinum system, interact with the ship there, skip until its the spitters turn.

### Expected Behavior

i expected i wouldnt have to deal with the karma of cheating by the NPC getting to use it against me XD

### Toybox Version

1.5.9c

### What game are you using Toybox on?

Rogue Trader

### Game Version

1.0.69

### Anything else?

i tried putting the saves and settings in but got an error saying it wasn't supported, sorry I cant help more.

**Comment by Aranwen** [comment]
> Is this still an issue on the latest version?

i don't have a save back far enough to test this specific location but the monsters in act 3 were able to abuse it as well and now they cant so I'm hoping its been fixed. nice job and ty for making the mod ^,^

i will be making a new character after this run is over so i will know for sure then.

**Comment by xADDBx** [comment]
Assuming fixed
