### ISSUE TITLE
RT: Remove talent requirements for *Abilities and Archetypes Only*

### ISSUE THREAD

**Issue by TKDancer** [xADDBx/ToyBox-RogueTrader#17]
### Is your feature request related to a problem?

not a problem but rather a suggestion: i enjoy not having talent restrictions when selecting abilities as the number of abilities we get to choose is already very limited but most have taxes that are just unnecessary but i dont have to just remove all talent requirements from other talent selections at all times

and similarly i think extending this to archetypes would also be nice

### Describe the solution you'd like

simply, if possible, add a version of the "no talent requirements" toggle in the level up tab that only applies to abilities, i.e this would make something like a Pyromancer's Inflame no longer require a specific Psy Rating talent and a different Ability pick

again, would also be nice to have this more selective restriction lifting to apply to archetypes as well for the sake of more build variety

**Comment by xADDBx** [comment]
Added Level Up => Ignore Archetypes Prerequisites. It's buggy. It allos picking e.g. Warrior => Master Tactician. This does not allow picking 2 archetypes from the same level or skipping one.

If there's a need to ability prequisite thingy then reopen in another issue
