### ISSUE TITLE
<title>Walking Feature not working

### ISSUE THREAD

**Issue by ProjectBuraizo** [xADDBx/ToyBox-RogueTrader#31]
### Description of the bug

Dear 
After installing toybox for the new dlc version, i notice the walk feature does not work anymore
If you would be able to look into this
thanks in advance.

### Steps To Reproduce

Open Unity Mod manager
- Adjust sliders - Maxdistance walk and maxdistance sprint
- Character stays in running animation

### Toybox Version

1.6

### What game are you using Toybox on?

Rogue Trader

**Comment by xADDBx** [comment]
You mean the "Walk at x distance; Run at x distance"?

**Comment by ProjectBuraizo** [comment]
yes exactly, either i'm doing something wrong but i tried putting the walk at x distance on 4. as i did prior to the dlc drop.
I put Run at x Distance on 6 so they dont overlap

But still the character only runs,

**Comment by xADDBx** [comment]
Fixed in 1.6.1
