### ISSUE TITLE
Object Highlight Toggle stops working (and blocks highlighting when holding key)

### ISSUE THREAD

**Issue by RyanHx** [xADDBx/ToyBox-RogueTrader#34]
### Description of the bug

With the **Object Highlight Toggle Mode** enabled, under certain conditions the game seems to stop highlighting anything (as in the default behaviour of not holding the highlight key), and pressing Tab stops doing anything. 

Using **Reset UI** in toybox does not fix the issue, neither does loading a save or returning to the main menu. Only restarting the game fixes it.

### Steps To Reproduce
Using the provided save file I took the following steps:
1. Switch on highlight if it is off
2. Report boss is dead on cogitator
3. Skipped the cutscene of camera moving from the arena to the top of the lift (might be relevant)
4. Exhausted all dialogue with the Wolves
5. Highlight is broken when control is given back in the next zone

### Expected Behavior

Highlight should continue to show character names and interactables. 
Highlight key (Tab) should turn this toggle on and off.

### Log Files

[GameLogFull.txt](https://github.com/user-attachments/files/17530744/GameLogFull.txt)
[Player.log](https://github.com/user-attachments/files/17530745/Player.log)

### Save File

[Manual_123_bug_report.zip](https://github.com/user-attachments/files/17530741/Manual_123_bug_report.zip)

### Screenshots

![image](https://github.com/user-attachments/assets/49a97fae-5564-453b-b3b7-9245909e87f4)
Highlight is off despite pressing tab.

### Settings

[Settings.zip](https://github.com/user-attachments/files/17530409/Settings.zip)

### Toybox Version

1.6.10

### Operating System

Windows 10

### What game are you using Toybox on?

Rogue Trader

### Game Version

1.2.1.19

**Comment by RyanHx** [comment]
Further testing I have been able to reproduce the issue with 100% consistency, and have updated the report. It is definitely cutscene/dialogue related. I have uploaded a new save (Manual_123_bug_report.zip) and logs, as well as the steps needed to trigger it with that save.

**Comment by xADDBx** [comment]
Does this version still have the issue? I just tried what could be an easy fix.
If that doesn't work, I'll either have to make it so that highlight toggle doesn't try to re-enable itself after combat/cutscenes or add some more complicated tracking in the background...
[ToyBox-1.6.11.zip](https://github.com/user-attachments/files/17531726/ToyBox-1.6.11.zip)

**Comment by RyanHx** [comment]
The issue still happens with that version unfortunately.

**Comment by xADDBx** [comment]
I can reproduce the issue without ToyBox installed...

**Comment by RyanHx** [comment]
Oh Owlcat... 

I'll send a bug report, sorry for the trouble!
