### ISSUE TITLE
Toybox added ability was lost after loading the archive

### ISSUE THREAD

**Issue by mztj94423** [xADDBx/ToyBox-RogueTrader#38]
### Is your feature request related to a problem?

I use ToyBox to added NPC's ability to the character, but when I loaded the archive, That ability was lost.

### Describe the solution you'd like

I not find the reason, But I found add 'm_Sources' to the '{%save_name}.7z/party.json', the ability does not seem to be lost with loading the archive.

This is the modified ability content:
###
    "$id": "3272",
    "$type": "Kingmaker.UnitLogic.Abilities.Ability, Code",
    "m_Hidden": false,
    "Data": {
        "$id": "3273",
        "m_CasterRef": "9fadd834969553569fb7e50eaad1a96d",
        "Blueprint": "fdb7ad9f95224672af0853c2fe3a48de",
        "Fact": {
            "$ref": "3272"
        },
        "UniqueId": "16060f901a6052418219161022f6de21",
        "DecorationColorNumber": -1,
        "DecorationBorderNumber": -1
    },
    "m_Components": [

    ],
    "m_Sources": [
        {
            "$id": "3274",  // inc id
            "m_Blueprint": "3a849d3674644c0085d5099ccf6813df"  // character's guid
        }
    ],
    "UsagesPerDayResource": null,
    "Blueprint": "fdb7ad9f95224672af0853c2fe3a48de",
    "UniqueId": "06ca9767d720505fb02e9a4500dacb25",
    "IsActive": true

**Comment by xADDBx** [comment]
If adding a source really does prevent the ability from being removed then that actually surprised me. I thought they just didn't serialize Abilities for RogueTrader. I'll look into it (maybe) in the next few dayss to see if something can be done about that.

**Comment by xADDBx** [comment]
Can you try this version of ToyBox to see whether it's fixed and report back? Thanks.

Direct DL Link: https://github.com/xADDBx/ToyBox-RogueTrader/actions/runs/12229398672/artifacts/2291888851

Link the the run if DDL didn't work: https://github.com/xADDBx/ToyBox-RogueTrader/actions/runs/12229398672

**Comment by mztj94423** [comment]
Thank you for your reply.I tried it and it did indeed take effect.
No other issues have been found, It looks like perfect.
