### ISSUE TITLE
Toybox Loot page doesn't list the loot

### ISSUE THREAD

**Issue by EternalLaughter** [xADDBx/ToyBox-RogueTrader#39]
### Description of the bug

The toybox loot page doesn't list the loot found on the map unless you've clicked the container for it already, or it's corpses\things you've killed. Same if i try to click the open mass loot bound key, nothing happens. Unless corpses\containers i've clicked.

If i use the option "Show everything when leaving map" then i get all the stuff in the cargo menu and the mass loot key shows it, but the details on the loot page are still blank, unless i go and click on the container and exit out.

### Steps To Reproduce

Go to place with loot\containers. Check the loot page and see it's not populated.
Click container, exit out, see loot contained being shown in loot page-

### Expected Behavior

I'd hope to have all the loot on the map shown.

### Toybox Version

1.7.4

### Operating System

Linux

### What game are you using Toybox on?

Rogue Trader

### Game Version

1.2.1.26

**Comment by xADDBx** [comment]
It only shows loot that was discovered already. 1.7.7 adds an option to show hidden loot in the checklist

**Comment by EternalLaughter** [comment]
Yay, thank you :)
