### ISSUE TITLE
Psyker Warp Table

### ISSUE THREAD

**Issue by x4dr** [xADDBx/ToyBox-RogueTrader#9]
### Is your feature request related to a problem?

Specifically Idira as an unsanction psyker apparently always has the chance to trigger major effects (including dieing and summoning a demon) 
Generally modifying what can happen when a psyker triggers the bonus effects seems cool

### Describe the solution you'd like

Ideally some form of loot table editing with variants for low/high warp

### Describe alternatives you've considered

just an option to disable additional perils of the warp occuring with veilthickness below a threshhold
disabling all perils of the warp
disabling just the ones that knock out your character

### Additional context

the discord quick version of this seems to work

**Comment by xADDBx** [comment]
Finally had some time to think. Possible implementation:

- Transpile `RuleCalculatePsychicPhenomenaEffect.OnTrigger`
- Replace `ldfld`s to the relevant array (e.g. `PerilsOfTheWarpMinor`) with a pop + call to a function which returns a custom array with wanted effects
- Add gui that allows customizing which effects should be enabled and which disabled (Browser?)

**Comment by xADDBx** [comment]
Should be in 1.5.21
